### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cym13** [aainz/AiJson#1]
In AiList.c the return line 21 leaks node which was allocated line 17.

The easier way to avoid that is to test the nullity of list before allocating the node, that would also be a teensy more efficient.

However in the long run the solution might be to change style. A style that works well for such error management is to use goto to enforce a single return point:

    int AiListInsert(AiList *list, void *data)
    {
       AiListNode *node = (AiListNode *) malloc(sizeof(*node));
       if(!node)
          goto ERR;
       if(!list)
          goto ERR;
       memset(node, 0, sizeof(*node));
       node->data = data;
       if(!list->first)
       {
          list->first = node;
          list->last  = node;
       }
       else
       {
          list->last->next = node;
          node->prev = list->last;
          list->last = node;
       }
       ++list->len;
       return 1;

    err:
       free(node);
       return 0;
    }

In this case it would be too much, but when you have many things to free and many possible exit points it saves you the trouble of having to think what to free where and not forget one. You just go in error and free it all. Note however that it also means that you have to have defined your variables beforehand and initilized them to NULL if not directly allocated for free to work correctly.

**Comment by aainz** [comment]
Fixed, thank you.
